GROUP_REPOS = [
{
    "name": "Gorillaerne",
    "gitLinks": ["https://github.com/Gorillaerne/Devops_Gorillas"],
    "backend": "https://gorillahub.dk",
    "frontend": "https://gorillahub.dk",
    "monitoring": "http://104.248.199.180:3000",
    "stack": ["Go","Gorilla/Mux","JavaScript","HTML","CSS","Docker","Nginx"],
    "documentation": [],
    "sla": "",
},
{
    "name": "EmperiaPizza",
    "gitLinks": ["https://github.com/EmperiaPizza/EmperiaSearch"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "ASCDevOps",
    "gitLinks": ["https://github.com/ASCDevOps/ASC_whoknows"],
    "backend": "https://ascsearch.dk",
    "frontend": "https://ascsearch.dk",
    "monitoring": "http://188.166.19.130:3000",
    "stack": ["GO", "SQLite","Docker","Nginx",],
    "documentation": [],
    "sla": "",
}, 
{
    "name": "ripmarkus",
    "gitLinks": ["https://github.com/ripmarkus/whoknows_ripmarkus"],
    "backend": "http://91.100.1.101",
    "frontend": "http://91.100.1.101",
    "monitoring": "",
    "stack": ["Ruby", "SQLite"],
    "documentation": [],
    "sla": "",
},
{
    "name": "nasOps",
    "gitLinks": ["https://github.com/nasOps/MonkKnows"],
    "backend": "https://monkknows.dk",
    "frontend": "https://monkknows.dk",
    "monitoring": "Postman",
    "stack": ["Ruby", "Sinatra", "SQLite", "Nginx", "Azure VM", "Docker", "GitHub Actions", "Let's Encrypt"],
    "documentation": [],
    "sla": "",
},
{
    "name": "BaseJumpers",
    "gitLinks": ["https://github.com/BaseJumpers/BaseJumperSearch"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "Knowledgeables",
    "gitLinks": ["https://github.com/Knowledgeables/Knowledge"],
    "backend": "https://www.knowledgeable.one",
    "frontend": "https://www.knowledgeable.one",
    "monitoring": "Prometheus, Postman",
    "stack": ["Golang","Nginx", "Azure VM", "SQLlite, Docker, Knex.js, Certbot"],
    "documentation": [],
    "sla": "",
},
{
    "name": "team36",
    "gitLinks": ["https://github.com/DevOps-team36/legacy-whoknows"],
    "backend": "https://huw.dk",
    "frontend": "https://huw.dk",
    "monitoring": "http://147.182.184.189:3000/d/ad9xb7b/team36",
    "stack": ["Go", "Ansible", "PostgreSQL", "Nginx", "Prometheus", "Grafana", "Loki"],
    "documentation": [],
    "sla": "",
},
{
    "name": "deploying-on-friday",
    "gitLinks": ["https://github.com/deploying-on-friday/dof"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
     "name": "SyntaxDevOpsSquad",
      "gitLinks": ["https://github.com/SyntaxDevopsSquad-SDS/devops-syntaxsquad"],
      "backend": "https://syntax-reborndev.com/",
      "frontend": "https://syntax-reborndev.com/",
      "monitoring": "https://monitor.syntax-reborndev.com/",
      "stack": ["GO, SQLite"],
      "documentation": [],
      "sla": "",
}  
]

