GROUP_REPOS = [
{
    "name": "Gorillaerne",
    "gitLinks": ["https://github.com/Gorillaerne/Devops_Gorillas"],
    "backend": "https://gorillahub.dk",
    "frontend": "https://gorillahub.dk",
    "monitoring": "",
    "stack": ["Go","Gorilla/Mux","JavaScript","HTML","CSS","Docker","Nginx"],
    "documentation": [],
    "sla": "",
},
{
    "name": "EmperiaPizza",
    "gitLinks": ["https://github.com/EmperiaPizza/EmperiaSearch"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "ASCDevOps",
    "gitLinks": ["https://github.com/ASCDevOps/ASC_whoknows"],
    "backend": "http://20.251.163.132:8080",
    "frontend": "http://20.251.163.132:8080",
    "monitoring": "",
    "stack": ["GO", "SQLite"],
    "documentation": [],
    "sla": "",
}, 
{
    "name": "ripmarkus",
    "gitLinks": ["https://github.com/ripmarkus/whoknows_ripmarkus"],
    "backend": "http://91.100.1.101",
    "frontend": "http://91.100.1.101",
    "monitoring": "",
    "stack": ["Ruby", "SQLite"],
    "documentation": [],
    "sla": "",
},
{
    "name": "nasOps",
    "gitLinks": ["https://github.com/nasOps/MonkKnows"],
    "backend": "http://4.225.161.111",
    "frontend": "http://4.225.161.111",
    "monitoring": "",
    "stack": ["Ruby", "Sinatra", "SQLite", "Nginx", "Azure VM"],
    "documentation": [],
    "sla": "",
},
{
    "name": "BaseJumpers",
    "gitLinks": ["https://github.com/BaseJumpers/BaseJumperSearch"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "Knowledgeables",
    "gitLinks": ["https://github.com/Knowledgeables/Knowledge"],
    "backend": "http://68.221.28.25",
    "frontend": "http://68.221.28.25",
    "monitoring": "",
    "stack": ["Golang","Nginx", "Azure VM", "SQLlite"],
    "documentation": [],
    "sla": "",
},
{
    "name": "team24",
    "gitLinks": ["https://github.com/DevOps-team24/legacy-whoknows"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "deploying-on-friday",
    "gitLinks": ["https://github.com/deploying-on-friday/dof"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
     "name": "SyntaxDevOpsSquad",
      "gitLinks": ["https://github.com/SyntaxDevopsSquad-SDS/devops-syntaxsquad"],
      "backend": "http://51.103.136.200:8080",
      "frontend": "http://51.103.136.200:8080",
      "monitoring": "",
      "stack": ["GO, SQLite"],
      "documentation": [],
      "sla": "",
}  
]

