GROUP_REPOS = [
{
    "name": "Gorillaerne",
    "gitLinks": ["https://github.com/Gorillaerne/Devops_Gorillas"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "EmperiaPizza",
    "gitLinks": ["https://github.com/EmperiaPizza/EmperiaSearch"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "ASCDevOps",
    "gitLinks": ["https://github.com/ASCDevOps/whoknows_variations"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
}, 
{
    "name": "ripmarkus",
    "gitLinks": ["https://github.com/ripmarkus/DevOps26"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "nasOps",
    "gitLinks": ["https://github.com/nasOps/MunkKnows"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "Knowledgeables",
    "gitLinks": ["https://github.com/Knowledgeables/Knowledge"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},


]
